### ISSUE TITLE
Crash when starting clangd

### ISSUE THREAD

**Issue by eclig** [blahgeek/emacs-lsp-booster#11]
I'm trying to use emacs-lsp-booster with eglot and clang.  The emacs-lsp-booster process crashes when starting clangd, here is the log from eglot:

> [internal] Tue Jan  9 12:52:13 2024:
> (:message "Running language server: emacs-lsp-booster --json-false-value :json-false -- emacs-lsp-booster --json-false-value :json-false -- /usr/local/bin/clangd")
> [client-request] (id:1) Tue Jan  9 12:52:13 2024:
> (:jsonrpc "2.0" :id 1 :method "initialize" :params
>           (:processId 25579 :rootPath "/home/xxx/yyy/projects/zzz/foobar/" :rootUri "file:///home/xxx/yyy/projects/zzz/foobar" :initializationOptions #s(hash-table size 1 test eql rehash-size 1.5 rehash-threshold 0.8125 data
>                                                                                                                                                                                                   ())
>                       :capabilities
>                       (:workspace
>                        (:applyEdit t :executeCommand
>                                    (:dynamicRegistration :json-false)
>                                    :workspaceEdit
>                                    (:documentChanges t)
>                                    :didChangeWatchedFiles
>                                    (:dynamicRegistration t)
>                                    :symbol
>                                    (:dynamicRegistration :json-false)
>                                    :configuration t :workspaceFolders t)
>                        :textDocument
>                        (:synchronization
>                         (:dynamicRegistration :json-false :willSave t :willSaveWaitUntil t :didSave t)
>                         :completion
>                         (:dynamicRegistration :json-false :completionItem
>                                               (:snippetSupport t :deprecatedSupport t :tagSupport
>                                                                (:valueSet
>                                                                 [1]))
>                                               :contextSupport t)
>                         :hover
>                         (:dynamicRegistration :json-false :contentFormat
>                                               ["markdown" "plaintext"])
>                         :signatureHelp
>                         (:dynamicRegistration :json-false :signatureInformation
>                                               (:parameterInformation
>                                                (:labelOffsetSupport t)
>                                                :activeParameterSupport t))
>                         :references
>                         (:dynamicRegistration :json-false)
>                         :definition
>                         (:dynamicRegistration :json-false :linkSupport t)
>                         :declaration
>                         (:dynamicRegistration :json-false :linkSupport t)
>                         :implementation
>                         (:dynamicRegistration :json-false :linkSupport t)
>                         :typeDefinition
>                         (:dynamicRegistration :json-false :linkSupport t)
>                         :documentSymbol
>                         (:dynamicRegistration :json-false :hierarchicalDocumentSymbolSupport t :symbolKind
>                                               (:valueSet
>                                                [1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]))
>                         :documentHighlight
>                         (:dynamicRegistration :json-false)
>                         :codeAction
>                         (:dynamicRegistration :json-false :codeActionLiteralSupport
>                                               (:codeActionKind
>                                                (:valueSet
>                                                 ["quickfix" "refactor" "refactor.extract" "refactor.inline" "refactor.rewrite" "source" "source.organizeImports"]))
>                                               :isPreferredSupport t)
>                         :formatting
>                         (:dynamicRegistration :json-false)
>                         :rangeFormatting
>                         (:dynamicRegistration :json-false)
>                         :rename
>                         (:dynamicRegistration :json-false)
>                         :publishDiagnostics
>                         (:relatedInformation :json-false :codeDescriptionSupport :json-false :tagSupport
>                                              (:valueSet
>                                               [1 2])))
>                        :experimental #s(hash-table size 1 test eql rehash-size 1.5 rehash-threshold 0.8125 data
>                                                    ()))
>                       :workspaceFolders
>                       [(:uri "file:///home/xxx/yyy/projects/zzz/foobar" :name "~/yyy/projects/zzz/foobar/")]))
> [stderr] [2024-01-09T11:52:13Z INFO  emacs_lsp_booster::app] Running server "emacs-lsp-booster" "--json-false-value" ":json-false" "--" "/usr/local/bin/clangd"
> [stderr] [2024-01-09T11:52:13Z INFO  emacs_lsp_booster::app] Will convert server json to bytecode! bytecode options: BytecodeOptions { object_type: Plist, null_value: Nil, false_value: Keyword("json-false") }
> [stderr] [2024-01-09T11:52:13Z INFO  emacs_lsp_booster::app] Running server "/usr/local/bin/clangd"
> [stderr] [2024-01-09T11:52:13Z INFO  emacs_lsp_booster::app] Will convert server json to bytecode! bytecode options: BytecodeOptions { object_type: Plist, null_value: Nil, false_value: Keyword("json-false") }
> [stderr] I[12:52:13.045] clangd version 17.0.0 (https://github.com/llvm/llvm-project df357a71dd7d10ee4bdc0bd22e6be048c5ad7088)
> [stderr] I[12:52:13.045] Features: linux+grpc
> [stderr] I[12:52:13.045] PID: 25781
> [stderr] I[12:52:13.045] Working directory: /home/xxx/yyy/projects/zzz/foobar
> [stderr] I[12:52:13.045] argv[0]: /usr/local/bin/clangd
> [stderr] I[12:52:13.045] Starting LSP over stdin/stdout
> [stderr] I[12:52:13.045] <-- initialize(1)
> [stderr] I[12:52:13.047] --> reply:initialize(1) 1 ms
> [stderr] thread '<unnamed>' panicked at /home/xxx/projects/emacs-lsp-booster/src/app.rs:139:91:
> [stderr] called `Result::unwrap()` on an `Err` value: expected value at line 1 column 1
> [stderr] 
> [stderr] Stack backtrace:
> [stderr]    0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
> [stderr]    1: emacs_lsp_booster::app::process_server_reader
> [stderr]    2: std::sys_common::backtrace::__rust_begin_short_backtrace
> [stderr]    3: core::ops::function::FnOnce::call_once{{vtable.shim}}
> [stderr]    4: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
> [stderr]              at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
> [stderr]    5: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
> [stderr]              at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
> [stderr]    6: std::sys::unix::thread::Thread::new::thread_start
> [stderr]              at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
> [stderr]    7: start_thread
> [stderr]              at ./nptl/pthread_create.c:442:8
> [stderr]    8: clone3
> [stderr]              at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
> [stderr] stack backtrace:
> [stderr] stack backtrace:
> [stderr]    0:     0x5559ef112fec - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
> [stderr]    1:     0x5559ef112fec - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
> [stderr]    2:     0x5559ef112fec - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
> [stderr]    3:     0x5559ef112fec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
> [stderr]    4:     0x5559ef13c270 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
> [stderr]    5:     0x5559ef13c270 - core::fmt::write::h3a39390d8560d9c9
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
> [stderr]    6:     0x5559ef110fff - std::io::Write::write_fmt::h5fc9997dfe05f882
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
> [stderr]    7:     0x5559ef112dd4 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
> [stderr]    8:     0x5559ef112dd4 - std::sys_common::backtrace::print::h23a2d212c6fff936
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
> [stderr]    9:     0x5559ef1147d7 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
> [stderr]   10:     0x5559ef11453f - std::panicking::default_hook::h6038f2eba384e475
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
> [stderr]   11:     0x5559ef06983e - emacs_lsp_booster::main::{{closure}}::hb076120cf24882ab
> [stderr]   12:     0x5559ef114de8 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h1f8f335eaa9cfaee
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2021:9
> [stderr]   13:     0x5559ef114de8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:783:13
> [stderr]   14:     0x5559ef114b3e - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
> [stderr]   15:     0x5559ef1134b6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
> [stderr]   16:     0x5559ef1148a2 - rust_begin_unwind
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
> [stderr]   17:     0x5559ef059705 - core::panicking::panic_fmt::hbf0e066aabfa482c
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
> [stderr]   18:     0x5559ef059ba3 - core::result::unwrap_failed::hddb4fea594200c52
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
> [stderr]   19:     0x5559ef05ed0f - std::sys_common::backtrace::__rust_begin_short_backtrace::hdf782c2abdcbc032
> [stderr]   20:     0x5559ef07dc97 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h94796a07809dd87c
> [stderr]   21:     0x5559ef119a25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc7eafaff61e32df9
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
> [stderr]   22:     0x5559ef119a25 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6ba4a5de48dd2304
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/alloc/src/boxed.rs:2007:9
> [stderr]   23:     0x5559ef119a25 - std::sys::unix::thread::Thread::new::thread_start::he469335aef763e45
> [stderr]                                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys/unix/thread.rs:108:17
> [stderr]   24:     0x7f0ae6406ac3 - start_thread
> [stderr]                                at ./nptl/pthread_create.c:442:8
> [stderr]   25:     0x7f0ae6498660 - clone3
> [stderr]                                at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
> [stderr]   26:                0x0 - <unknown>
> [stderr] E[12:52:13.145] Transport error: Input/output error
> [stderr] I[12:52:13.145] LSP finished, exiting with status 1
> [internal] Tue Jan  9 12:52:13 2024:
> (:message "Connection state changed" :change "exited abnormally with code 1\n")
> 
> ----------b---y---e---b---y---e----------
> [stderr] 
> [stderr] 
> [stderr] nil
> [stderr] nil
> [stderr] Process EGLOT (foobar/(c++-mode c-mode)) stderr finished

Am I doing something wrong?  Thanks for your time!

**Comment by blahgeek** [comment]
Apparently the `emacs-lsp-booster` wrapper is used twice:

> "Running language server: emacs-lsp-booster --json-false-value :json-false -- emacs-lsp-booster --json-false-value :json-false -- /usr/local/bin/clangd"


@jdtsmith will your eglot helper script cause this double-wrapper command issue in some case? This issue has been reported twice (also https://github.com/blahgeek/emacs-lsp-booster/issues/10 )

**Comment by jdtsmith** [comment]
No it adds a symbol property specifically to avoid this.  The user could reset this property with eglot-booster-reset and then accidentally double modify.  I use it or testing. Solution: don't do that :) (show your config).

**Comment by eclig** [comment]
You are right guys, I've messed up my config.  Restarting Emacs solved the trouble, thank you and sorry for the noise!
