### ISSUE TITLE
Adding module import/require code actions don't seem to work

### ISSUE THREAD

**Issue by anonimitoraf** [blahgeek/emacs-lsp-booster#14]
Great project! Been using this since release

I've just noticed that when I use a "Add require" code action (specifically for clojure-lsp), nothing happens.

I've also noticed that the code action text has a trailing `\327 1`

https://github.com/blahgeek/emacs-lsp-booster/assets/15933322/2140d6b9-60c2-4fb8-b315-8a75195ada57

I've tried multiple times with vs without emacs-lsp-booster. Without it, this code action works fine

**Comment by anonimitoraf** [comment]
For comparison, here's the experience without emacs-lsp-booster:

https://github.com/blahgeek/emacs-lsp-booster/assets/15933322/552ef806-265b-47da-baed-924aaab55ffb

**Comment by blahgeek** [comment]
Hello there,

Could you please set [`lsp-log-io`](https://emacs-lsp.github.io/lsp-mode/page/troubleshooting/#log-client-server-json) to `t` and reproduce the issue both with or without emacs-lsp-booster, then post here the json message from the debug buffer?

Thanks

**Comment by blahgeek** [comment]
Also, please make sure to test with the latest version (https://github.com/blahgeek/emacs-lsp-booster/releases). Recent changes contain some fix about the bytecode translation.

**Comment by anonimitoraf** [comment]
Ah thanks! Doesn't seem to happen with the latest version
