### ISSUE TITLE
Could I update the README file for installing lsp-booster

### ISSUE THREAD

**Issue by Watynecc** [blahgeek/emacs-lsp-booster#2]
From the eglot gist
https://gist.github.com/jdtsmith/d936801a4d7fd981bedf2e59dacd675e

**Comment by Watynecc** [comment]
huh even with that I can't find the command eglot-booster ,-, my bad

**Comment by jdtsmith** [comment]
Give it a test and report how it works first after a day of use or so.  Then it's reasonable to update the README to offer options for lsp-mode or eglot.  Did you M-x eval-buffer that gist?

**Comment by chookity-pokk** [comment]
@Watynecc All you need to do is copy/paste that file into you init.el. It will read that as a function that you've written and you will be able to call it. Also, this conversation should probably be happening in #1, or at least that's my two cents.

**Comment by Watynecc** [comment]
> @Watynecc All you need to do is copy/paste that file into you init.el. It will read that as a function that you've written and you will be able to call it. Also, this conversation should probably be happening in #1, or at least that's my two cents.

Excuse me ;-;

**Comment by chookity-pokk** [comment]
No worries! Just want to make sure it all stays in the relevant thread so that it is easier for people to find.

**Comment by blahgeek** [comment]
I've updated the README to include more instructions about building binary and added link to elot instructions. Please let me know if you have further suggestions!
