### ISSUE TITLE
Wrong version in cargo toml

### ISSUE THREAD

**Issue by Schievel1** [blahgeek/emacs-lsp-booster#20]
Minor thing, but I just stumbled upon this when auto generating package recipes. 

Version 0.2.0 has 0.1.0 in cargo.toml

**Comment by blahgeek** [comment]
Thanks for your report. Since the version in cargo.toml is only used for publishing packages as library, I do not intend to take extra effort to keep it up-to-date. I will change it to default value ("0.0.0") and add a comment.
