### ISSUE TITLE
`emacs-lsp-booster` without JSON translation to Elisp bytecode

### ISSUE THREAD

**Issue by maxecharel** [blahgeek/emacs-lsp-booster#25]
Hi @blahgeek,
Before anything else, thank you for your great work!

As mentioned in the readme, `emacs-lsp-booster` tackles different issues:
```
1. Json parsing in Emacs is slow
2. The server may block on sending data to emacs when the buffer is full, because Emacs is consuming the data too slowly
3. Similarly, Emacs may block while attempting to send data to the server (hence blocking the Emacs UI), because the server may be busy
```
In Emacs 30, point 1 is now handled by the brand new JSON parser. However, `emacs-lsp-booster` is still useful for points 2 and 3. Do you think it would be possible and relevant to develop a version of `emacs-lsp-booster` that would only handle IO buffering while letting the new JSON parser do its job?

**Comment by blahgeek** [comment]
Hello,

Yes, the `--disable-bytecode` flag does exactly that.

**Comment by maxecharel** [comment]
Thanks a lot for the quick answer, and for the information regarding the `--disable-bytecode` flag. Would be nice to have this as an option in `eglot-booster`, I'll open an issue.
